apiVersion: v1
kind: Service
metadata:
  name: app-one-svc
spec:
  type: LoadBalancer
  selector:
    app: app-one
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https