kind: Deployment
apiVersion: apps/v1
metadata:
  name: elasticsearch
spec:
  selector:
    matchLabels:
        app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      volumes:
        - name: data
          nfs:
            path: /mnt/disk/elasticsearch
            server: 10.150.16.171
      containers:
        - name: elasticsearch
          image: elasticsearch:7.4.2
          env:
            - name: discovery.type
              value: "single-node"
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: discovery
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: data
---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
spec:
  clusterIP: None
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
      name: http
    - port: 9300
      targetPort: 9300
      name: discovery
---
#kind: Ingress
#apiVersion: extensions/v1beta1
#metadata:
#  name: elasticsearch-ingress
#spec:
#  rules:
#  - http:
#      paths:
#      - path: /
#        backend:
#          serviceName: elasticsearch
#          servicePort: 9200