apiVersion: v1
kind: Pod
metadata:
  name: downward
spec:
  containers:
  - name: main
    image: busybox
    command: ["sleep", "9999999"]
    resources:
      requests:
        cpu: 15m
        memory: 100Ki
      limits:
        cpu: 100m
        memory: 4Mi
    volumeMounts:
      - mountPath: /etc/downward
        name: downward
  volumes:
    - name: downward
      downwardAPI:
        items:
          - path: "podName"
            fieldRef:
              fieldPath: metadata.name
          - path: "cpuRequestSize"
            resourceFieldRef:
              containerName: main
              resource: requests.cpu
          - path: "cpuLimitSize"
            resourceFieldRef:
              containerName: main
              resource: limits.memory