apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: ssd-monitor
spec:
  selector:
    matchLabels:
      app: ssd-monitor
  template:
    metadata:
      labels:
        app: ssd-monitor
    spec:
        nodeSelector:
          disk: ssd
        containers:
          - name: ssd-monitor
            image: rajat965ng/kubia:v1
