apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2
  namespace: custom-namespace
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
  - image: rajat965ng/kubia:v1
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP