apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  # use hostpath in case of minikube or create nfs server like in nfs-server.yaml
  hostPath:
    path: /tmp/mongodb
# when working with GCP
#  gcePersistentDisk:
#    pdName: mongodb
#    fsType: ext4