kind: ServiceAccount
apiVersion: v1
metadata:
  name: vault-auth
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
metadata:
  name: role-token-review-binding
subjects:
  - kind: ServiceAccount
    name: vault-auth
    namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example
rules:
  - verbs: ["*"]
    apiGroups: [""]
    resources: ["secrets"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: example-role-binding
subjects:
  - kind: ServiceAccount
    name: vault-auth
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: example