#Sample Spring boot application that connects with (vault + mongo).
kind: ConfigMap
apiVersion: v1
metadata:
  name: java-app
data:
  mongoHost: mongo
  vaultHost: vault
  vaultToken: myroot
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: java-app
spec:
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: app
          image: rajat965ng/vault-java
          env:
            - name: mongoHost
              valueFrom:
                configMapKeyRef:
                  key: mongoHost
                  name: java-app
            - name: vaultHost
              valueFrom:
                configMapKeyRef:
                  key: vaultHost
                  name: java-app
            - name: vaultToken
              valueFrom:
                configMapKeyRef:
                  key: vaultToken
                  name: java-app
          ports:
            - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: java-app
spec:
  selector:
    app: java-app
  ports:
    - port: 80
      targetPort: 8080


