kind: ConfigMap
apiVersion: v1
metadata:
  name: logstash
data:
  beat.conf: |
    input {
      beats {
        port => "5044"
      }
    }
    filter {
       grok {
          match => { "message" => "%{COMBINEDAPACHELOG}"}
       }
       geoip {
          source => "clientip"
       }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "%{[fields][appcode]}-%{[fields][env]}-%{+YYYY.MM.dd}"
        manage_template => false
      }
      stdout { codec => rubydebug }
    }

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: logstash
spec:
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      volumes:
        - name: beat-config
          configMap:
            name: logstash
            items:
              - key: beat.conf
                path: beat.conf
      containers:
        - name: logstash
          image: logstash:7.4.2
          volumeMounts:
            - mountPath: /usr/share/logstash/pipeline/
              name: beat-config
              readOnly: true
          ports:
            - containerPort: 5044
---
kind: Service
apiVersion: v1
metadata:
  name: logstash
spec:
  selector:
    app: logstash
  ports:
  - port: 5044
    targetPort: 5044

---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: logstash-ingress
spec:
  rules:
  - http:
      paths:
      - path: /logstash
        backend:
          serviceName: logstash
          servicePort: 80


#curl -X POST  http://10.244.1.47:8080 -d "one more log to debug"
#curl -X DELETE "elasticsearch:9200/jenkins?pretty"

#curl -X POST http://logstash:80 -d "log from container"