apiVersion: v1
kind: Pod
metadata:
  name: dudu-html-generator
spec:
  containers:
    - name: html-generator
      image: luksa/fortune:env
      volumeMounts:
        - mountPath: /var/htdocs
          name: html
#      env:
#        - name: INTERVAL
#          valueFrom:
#            configMapKeyRef:
#              key: dudu-config
#              name: config
    - name: webserver
      image: nginx:alpine
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
          readOnly: true
        - name: config
          mountPath: /etc/nginx/conf.d
          readOnly: true
        - name: certs
          mountPath: /etc/nginx/certs/
          readOnly: true
      ports:
        - containerPort: 80
        - containerPort: 443
  volumes:
    - name: html
      emptyDir: {}
    - name: certs
      secret:
        secretName: dudu-https
    - name: config
      configMap:
        name: dudu-config
        items:
          - key: dudu-config.conf
            path: https.conf
