// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator/calcpb/calculator.proto

package calcpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Input struct {
	FirstNum             int64    `protobuf:"varint,1,opt,name=firstNum,proto3" json:"firstNum,omitempty"`
	SecondNum            int64    `protobuf:"varint,2,opt,name=secondNum,proto3" json:"secondNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_f664ca1c5a6f0507, []int{0}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetFirstNum() int64 {
	if m != nil {
		return m.FirstNum
	}
	return 0
}

func (m *Input) GetSecondNum() int64 {
	if m != nil {
		return m.SecondNum
	}
	return 0
}

type Request struct {
	Input                *Input   `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_f664ca1c5a6f0507, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetInput() *Input {
	if m != nil {
		return m.Input
	}
	return nil
}

type Response struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_f664ca1c5a6f0507, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type MeteoricNumber struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeteoricNumber) Reset()         { *m = MeteoricNumber{} }
func (m *MeteoricNumber) String() string { return proto.CompactTextString(m) }
func (*MeteoricNumber) ProtoMessage()    {}
func (*MeteoricNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_f664ca1c5a6f0507, []int{3}
}

func (m *MeteoricNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeteoricNumber.Unmarshal(m, b)
}
func (m *MeteoricNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeteoricNumber.Marshal(b, m, deterministic)
}
func (m *MeteoricNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeteoricNumber.Merge(m, src)
}
func (m *MeteoricNumber) XXX_Size() int {
	return xxx_messageInfo_MeteoricNumber.Size(m)
}
func (m *MeteoricNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_MeteoricNumber.DiscardUnknown(m)
}

var xxx_messageInfo_MeteoricNumber proto.InternalMessageInfo

func (m *MeteoricNumber) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type PrimeFactor struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeFactor) Reset()         { *m = PrimeFactor{} }
func (m *PrimeFactor) String() string { return proto.CompactTextString(m) }
func (*PrimeFactor) ProtoMessage()    {}
func (*PrimeFactor) Descriptor() ([]byte, []int) {
	return fileDescriptor_f664ca1c5a6f0507, []int{4}
}

func (m *PrimeFactor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeFactor.Unmarshal(m, b)
}
func (m *PrimeFactor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeFactor.Marshal(b, m, deterministic)
}
func (m *PrimeFactor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeFactor.Merge(m, src)
}
func (m *PrimeFactor) XXX_Size() int {
	return xxx_messageInfo_PrimeFactor.Size(m)
}
func (m *PrimeFactor) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeFactor.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeFactor proto.InternalMessageInfo

func (m *PrimeFactor) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type NumSeries struct {
	Num                  int64    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NumSeries) Reset()         { *m = NumSeries{} }
func (m *NumSeries) String() string { return proto.CompactTextString(m) }
func (*NumSeries) ProtoMessage()    {}
func (*NumSeries) Descriptor() ([]byte, []int) {
	return fileDescriptor_f664ca1c5a6f0507, []int{5}
}

func (m *NumSeries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumSeries.Unmarshal(m, b)
}
func (m *NumSeries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumSeries.Marshal(b, m, deterministic)
}
func (m *NumSeries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumSeries.Merge(m, src)
}
func (m *NumSeries) XXX_Size() int {
	return xxx_messageInfo_NumSeries.Size(m)
}
func (m *NumSeries) XXX_DiscardUnknown() {
	xxx_messageInfo_NumSeries.DiscardUnknown(m)
}

var xxx_messageInfo_NumSeries proto.InternalMessageInfo

func (m *NumSeries) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type SeriesSum struct {
	Num                  int64    `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SeriesSum) Reset()         { *m = SeriesSum{} }
func (m *SeriesSum) String() string { return proto.CompactTextString(m) }
func (*SeriesSum) ProtoMessage()    {}
func (*SeriesSum) Descriptor() ([]byte, []int) {
	return fileDescriptor_f664ca1c5a6f0507, []int{6}
}

func (m *SeriesSum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SeriesSum.Unmarshal(m, b)
}
func (m *SeriesSum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SeriesSum.Marshal(b, m, deterministic)
}
func (m *SeriesSum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SeriesSum.Merge(m, src)
}
func (m *SeriesSum) XXX_Size() int {
	return xxx_messageInfo_SeriesSum.Size(m)
}
func (m *SeriesSum) XXX_DiscardUnknown() {
	xxx_messageInfo_SeriesSum.DiscardUnknown(m)
}

var xxx_messageInfo_SeriesSum proto.InternalMessageInfo

func (m *SeriesSum) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

type Account struct {
	Principal            int64    `protobuf:"varint,1,opt,name=principal,proto3" json:"principal,omitempty"`
	Rate                 int64    `protobuf:"varint,2,opt,name=rate,proto3" json:"rate,omitempty"`
	TimeInYears          int64    `protobuf:"varint,3,opt,name=timeInYears,proto3" json:"timeInYears,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_f664ca1c5a6f0507, []int{7}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetPrincipal() int64 {
	if m != nil {
		return m.Principal
	}
	return 0
}

func (m *Account) GetRate() int64 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *Account) GetTimeInYears() int64 {
	if m != nil {
		return m.TimeInYears
	}
	return 0
}

type SimpleInterest struct {
	Interest             int64    `protobuf:"varint,1,opt,name=interest,proto3" json:"interest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimpleInterest) Reset()         { *m = SimpleInterest{} }
func (m *SimpleInterest) String() string { return proto.CompactTextString(m) }
func (*SimpleInterest) ProtoMessage()    {}
func (*SimpleInterest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f664ca1c5a6f0507, []int{8}
}

func (m *SimpleInterest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleInterest.Unmarshal(m, b)
}
func (m *SimpleInterest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleInterest.Marshal(b, m, deterministic)
}
func (m *SimpleInterest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleInterest.Merge(m, src)
}
func (m *SimpleInterest) XXX_Size() int {
	return xxx_messageInfo_SimpleInterest.Size(m)
}
func (m *SimpleInterest) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleInterest.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleInterest proto.InternalMessageInfo

func (m *SimpleInterest) GetInterest() int64 {
	if m != nil {
		return m.Interest
	}
	return 0
}

func init() {
	proto.RegisterType((*Input)(nil), "calculator.Input")
	proto.RegisterType((*Request)(nil), "calculator.Request")
	proto.RegisterType((*Response)(nil), "calculator.Response")
	proto.RegisterType((*MeteoricNumber)(nil), "calculator.MeteoricNumber")
	proto.RegisterType((*PrimeFactor)(nil), "calculator.PrimeFactor")
	proto.RegisterType((*NumSeries)(nil), "calculator.NumSeries")
	proto.RegisterType((*SeriesSum)(nil), "calculator.SeriesSum")
	proto.RegisterType((*Account)(nil), "calculator.Account")
	proto.RegisterType((*SimpleInterest)(nil), "calculator.SimpleInterest")
}

func init() { proto.RegisterFile("calculator/calcpb/calculator.proto", fileDescriptor_f664ca1c5a6f0507) }

var fileDescriptor_f664ca1c5a6f0507 = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0x4b, 0x8b, 0x13, 0x41,
	0x10, 0xc7, 0x33, 0x3b, 0x26, 0x3b, 0xa9, 0xc0, 0xe2, 0xb6, 0xab, 0x86, 0x41, 0x61, 0x69, 0x41,
	0xf7, 0x20, 0x9b, 0x30, 0x9e, 0x3d, 0x44, 0x45, 0x88, 0x60, 0x90, 0x99, 0x93, 0x82, 0x87, 0x49,
	0x5b, 0x42, 0xc3, 0xf4, 0xc3, 0x7e, 0xe4, 0x2b, 0xf9, 0x35, 0xa5, 0x67, 0x3a, 0xf3, 0x00, 0xf7,
	0x56, 0xf5, 0xff, 0x57, 0xaa, 0xba, 0x7e, 0x95, 0x01, 0xca, 0xea, 0x86, 0xf9, 0xa6, 0x76, 0xca,
	0x6c, 0x42, 0xa8, 0x8f, 0x9b, 0x41, 0xb9, 0xd7, 0x46, 0x39, 0x45, 0x60, 0x50, 0xe8, 0x0e, 0xe6,
	0x7b, 0xa9, 0xbd, 0x23, 0x39, 0x64, 0xbf, 0xb9, 0xb1, 0xee, 0xe0, 0xc5, 0x3a, 0xb9, 0x4d, 0xee,
	0xd2, 0xb2, 0xcf, 0xc9, 0x0b, 0x58, 0x5a, 0x64, 0x4a, 0xfe, 0x0a, 0xe6, 0x45, 0x6b, 0x0e, 0x02,
	0x2d, 0xe0, 0xb2, 0xc4, 0x3f, 0x1e, 0xad, 0x23, 0x6f, 0x60, 0xce, 0x43, 0xb7, 0xb6, 0xc3, 0xaa,
	0xb8, 0xbe, 0x1f, 0xcd, 0x6e, 0xc7, 0x94, 0x9d, 0x4f, 0x29, 0x64, 0x25, 0x5a, 0xad, 0xa4, 0x45,
	0xf2, 0x0c, 0x16, 0x06, 0xad, 0x6f, 0x5c, 0x9c, 0x1b, 0x33, 0xfa, 0x1a, 0xae, 0xbe, 0xa2, 0x43,
	0x65, 0x38, 0x3b, 0x78, 0x71, 0x44, 0x43, 0x6e, 0x60, 0x7e, 0xaa, 0x1b, 0x8f, 0xb1, 0xb0, 0x4b,
	0xe8, 0x2b, 0x58, 0x7d, 0x33, 0x5c, 0xe0, 0xe7, 0x9a, 0x39, 0xf5, 0x50, 0xd1, 0x4b, 0x58, 0x1e,
	0xbc, 0xa8, 0xd0, 0x70, 0xb4, 0xe4, 0x31, 0xa4, 0xb2, 0x5f, 0x33, 0x84, 0xc1, 0xee, 0xbc, 0xca,
	0x8b, 0xff, 0xd8, 0x3f, 0xe1, 0x72, 0xc7, 0x98, 0xf2, 0xd2, 0x05, 0x16, 0xda, 0x70, 0xc9, 0xb8,
	0xae, 0x9b, 0x58, 0x32, 0x08, 0x84, 0xc0, 0x23, 0x53, 0x3b, 0x8c, 0x90, 0xda, 0x98, 0xdc, 0xc2,
	0xca, 0x71, 0x81, 0x7b, 0xf9, 0x1d, 0x6b, 0x63, 0xd7, 0x69, 0x6b, 0x8d, 0x25, 0xfa, 0x16, 0xae,
	0x2a, 0x2e, 0x74, 0x83, 0x7b, 0xe9, 0xd0, 0x04, 0x90, 0x39, 0x64, 0x3c, 0xc6, 0xe7, 0x6b, 0x9c,
	0xf3, 0xe2, 0xef, 0x05, 0x5c, 0x7f, 0xec, 0xb9, 0x56, 0x68, 0x4e, 0x9c, 0x21, 0x29, 0x20, 0x0d,
	0x6f, 0x7f, 0x32, 0x46, 0x1e, 0xcf, 0x92, 0xdf, 0x4c, 0xc5, 0x8e, 0x3b, 0x9d, 0x91, 0x0a, 0xd6,
	0x2d, 0xb9, 0x0e, 0xef, 0x27, 0x64, 0x4a, 0x68, 0x65, 0xb9, 0xe3, 0x4a, 0x92, 0x7c, 0xfc, 0x9b,
	0xe9, 0x1d, 0xf2, 0xe7, 0x63, 0x6f, 0xc4, 0x9e, 0xce, 0xb6, 0x09, 0x79, 0x0f, 0xcb, 0xaa, 0x27,
	0xfd, 0x74, 0x5c, 0xd9, 0x1f, 0x20, 0x9f, 0xc8, 0x3d, 0x78, 0x3a, 0xbb, 0x4b, 0xc8, 0x97, 0x61,
	0xb9, 0x01, 0xc7, 0x64, 0xab, 0x78, 0x89, 0x7c, 0xf2, 0xc2, 0x29, 0xbf, 0xd0, 0x69, 0x9b, 0x7c,
	0xc8, 0x7e, 0x2c, 0xba, 0x6f, 0xe0, 0xb8, 0x68, 0xff, 0xf9, 0xef, 0xfe, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x06, 0xbd, 0xf0, 0x19, 0x1f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	Sum(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	PrimeNumberDecomposition(ctx context.Context, in *MeteoricNumber, opts ...grpc.CallOption) (CalculatorService_PrimeNumberDecompositionClient, error)
	SumSeries(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_SumSeriesClient, error)
	CalculateInterest(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_CalculateInterestClient, error)
}

type calculatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorServiceClient(cc *grpc.ClientConn) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Sum(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/calculator.CalculatorService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) PrimeNumberDecomposition(ctx context.Context, in *MeteoricNumber, opts ...grpc.CallOption) (CalculatorService_PrimeNumberDecompositionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculatorService_serviceDesc.Streams[0], "/calculator.CalculatorService/PrimeNumberDecomposition", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServicePrimeNumberDecompositionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculatorService_PrimeNumberDecompositionClient interface {
	Recv() (*PrimeFactor, error)
	grpc.ClientStream
}

type calculatorServicePrimeNumberDecompositionClient struct {
	grpc.ClientStream
}

func (x *calculatorServicePrimeNumberDecompositionClient) Recv() (*PrimeFactor, error) {
	m := new(PrimeFactor)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) SumSeries(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_SumSeriesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculatorService_serviceDesc.Streams[1], "/calculator.CalculatorService/SumSeries", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceSumSeriesClient{stream}
	return x, nil
}

type CalculatorService_SumSeriesClient interface {
	Send(*NumSeries) error
	CloseAndRecv() (*SeriesSum, error)
	grpc.ClientStream
}

type calculatorServiceSumSeriesClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceSumSeriesClient) Send(m *NumSeries) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorServiceSumSeriesClient) CloseAndRecv() (*SeriesSum, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SeriesSum)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) CalculateInterest(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_CalculateInterestClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculatorService_serviceDesc.Streams[2], "/calculator.CalculatorService/CalculateInterest", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceCalculateInterestClient{stream}
	return x, nil
}

type CalculatorService_CalculateInterestClient interface {
	Send(*Account) error
	Recv() (*SimpleInterest, error)
	grpc.ClientStream
}

type calculatorServiceCalculateInterestClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceCalculateInterestClient) Send(m *Account) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorServiceCalculateInterestClient) Recv() (*SimpleInterest, error) {
	m := new(SimpleInterest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
type CalculatorServiceServer interface {
	Sum(context.Context, *Request) (*Response, error)
	PrimeNumberDecomposition(*MeteoricNumber, CalculatorService_PrimeNumberDecompositionServer) error
	SumSeries(CalculatorService_SumSeriesServer) error
	CalculateInterest(CalculatorService_CalculateInterestServer) error
}

// UnimplementedCalculatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalculatorServiceServer struct {
}

func (*UnimplementedCalculatorServiceServer) Sum(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (*UnimplementedCalculatorServiceServer) PrimeNumberDecomposition(req *MeteoricNumber, srv CalculatorService_PrimeNumberDecompositionServer) error {
	return status.Errorf(codes.Unimplemented, "method PrimeNumberDecomposition not implemented")
}
func (*UnimplementedCalculatorServiceServer) SumSeries(srv CalculatorService_SumSeriesServer) error {
	return status.Errorf(codes.Unimplemented, "method SumSeries not implemented")
}
func (*UnimplementedCalculatorServiceServer) CalculateInterest(srv CalculatorService_CalculateInterestServer) error {
	return status.Errorf(codes.Unimplemented, "method CalculateInterest not implemented")
}

func RegisterCalculatorServiceServer(s *grpc.Server, srv CalculatorServiceServer) {
	s.RegisterService(&_CalculatorService_serviceDesc, srv)
}

func _CalculatorService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Sum(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_PrimeNumberDecomposition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MeteoricNumber)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).PrimeNumberDecomposition(m, &calculatorServicePrimeNumberDecompositionServer{stream})
}

type CalculatorService_PrimeNumberDecompositionServer interface {
	Send(*PrimeFactor) error
	grpc.ServerStream
}

type calculatorServicePrimeNumberDecompositionServer struct {
	grpc.ServerStream
}

func (x *calculatorServicePrimeNumberDecompositionServer) Send(m *PrimeFactor) error {
	return x.ServerStream.SendMsg(m)
}

func _CalculatorService_SumSeries_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).SumSeries(&calculatorServiceSumSeriesServer{stream})
}

type CalculatorService_SumSeriesServer interface {
	SendAndClose(*SeriesSum) error
	Recv() (*NumSeries, error)
	grpc.ServerStream
}

type calculatorServiceSumSeriesServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceSumSeriesServer) SendAndClose(m *SeriesSum) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorServiceSumSeriesServer) Recv() (*NumSeries, error) {
	m := new(NumSeries)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CalculatorService_CalculateInterest_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).CalculateInterest(&calculatorServiceCalculateInterestServer{stream})
}

type CalculatorService_CalculateInterestServer interface {
	Send(*SimpleInterest) error
	Recv() (*Account, error)
	grpc.ServerStream
}

type calculatorServiceCalculateInterestServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceCalculateInterestServer) Send(m *SimpleInterest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorServiceCalculateInterestServer) Recv() (*Account, error) {
	m := new(Account)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _CalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _CalculatorService_Sum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumberDecomposition",
			Handler:       _CalculatorService_PrimeNumberDecomposition_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SumSeries",
			Handler:       _CalculatorService_SumSeries_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "CalculateInterest",
			Handler:       _CalculatorService_CalculateInterest_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "calculator/calcpb/calculator.proto",
}
