kind: ConfigMap
apiVersion: v1
metadata:
  name: filebeat
data:
  filebeat.yml: |
    filebeat.config:
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false

    processors:
    - add_cloud_metadata: ~

    filebeat.inputs:
    - type: tcp
      max_message_size: 10MiB
      host: "localhost:9000"

    output.elasticsearch:
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
      #username: '${ELASTICSEARCH_USERNAME:}'
      #password: '${ELASTICSEARCH_PASSWORD:}'
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      volumes:
      - name: config
        configMap:
          name: filebeat
          items:
          - key: filebeat.yml
            path: filebeat.yml
      containers:
      - name: filebeat
        image: filebeat:7.4.2
        volumeMounts:
          - mountPath: /usr/share/filebeat/filebeat.yml
            name: config
            readOnly: true
        ports:
        - containerPort: 9000
---
kind: Service
apiVersion: v1
metadata:
  name: filebeat
spec:
  selector:
    app: filebeat
  ports:
  - port: 80
    targetPort: 9000

---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: filebeat-ingress
spec:
  rules:
  - http:
      paths:
      - path: /filebeat
        backend:
          serviceName: filebeat
          servicePort: 80


#curl -X POST  http://10.244.1.41:8080 -d "{hi gpssa}"
#curl -X DELETE "elasticsearch:9200/jenkins?pretty"