kind: StatefulSet
apiVersion: apps/v1
metadata:
  namespace: default
  name: nexus
spec:
  selector:
    matchLabels:
      app: nexus
  serviceName: "nexus"
  template:
    metadata:
      labels:
        app: nexus
    spec:
      volumes:
        - name: nexus-data
          nfs:
            path: /mnt/disk/nexus/data
            server: 10.150.16.171
      containers:
        - name: nexus
          image: sonatype/nexus3
          env:
            - name: NEXUS_CONTEXT
              value: nexus
          ports:
            - containerPort: 8081
              name: http-main
            - containerPort: 8124
              name: http-docker
            - containerPort: 8123
              name: https-docker
          volumeMounts:
            - mountPath: /nexus-data
              name: nexus-data
---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: nexus-http
spec:
  selector:
    app: nexus
  ports:
    - port: 80
      targetPort: 8081
      name: http-main
---
kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: nexus-docker
spec:
  type: NodePort
  selector:
    app: nexus
  ports:
  - port: 8124
    targetPort: 8124
    name: http-docker
    nodePort: 32000
  - port: 8123
    targetPort: 8123
    name: https-docker
    nodePort: 32022
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  namespace: default
  name: nexus
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
    - http:
        paths:
          - path: /nexus
            backend:
              serviceName: nexus-http
              servicePort: 80